# Generated by Django 4.0.3 on 2022-04-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_categoria_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
    ]
